### ISSUE TITLE
Asset connections using SSH key instead of password

### ISSUE THREAD

**Issue by joelwanner** [OneIdentity/safeguard-ansible#1]
Hi folks,

First of all, thank you for providing this plugin. It works great when using passwords for SSH authentication to assets. However, I have not been able to find a way to use private key credentials at all.

The [Examples](https://github.com/OneIdentity/safeguard-ansible/tree/main/collection/oneidentity/safeguard/plugins#examples) section in the documentation contains a playbook that fetches an SSH private key. See the following excerpt:

```yaml
- name: SPP Test Playbook
  hosts: all
  vars:
    spp_credential_apikey: +IWSU/0msm98hUUUen5xOnYZZytVN2o9hLFxVr9S80Q=
    my_spp_appliance: 192.168.1.234
    [...]
    a2apasswordconnectioninfo:
      spp_appliance: "{{ my_spp_appliance }}"
      [...]
      spp_credential_type: password
    a2aprivatekeyconnectioninfo:
      spp_appliance: "{{ my_spp_appliance }}"
      [...]
      spp_credential_type: privatekey
  tasks:
    - name: Get the account password
      set_fact:
        my_password: "{{lookup('oneidentity.safeguardcollection.safeguardcredentials', spp_credential_apikey, a2aconnection=a2apasswordconnectioninfo)}}"
        my_privatekey: "{{lookup('oneidentity.safeguardcollection.safeguardcredentials', spp_credential_apikey, a2aconnection=a2aprivatekeyconnectioninfo)}}"
```

I'm wondering if there is any way to pass the private key obtained via the lookup command to Ansible to use for authentication. The key lookup works perfectly, I'm just not seeing a way to make Ansible use it directly.

[This section in the Ansible docs](https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters) shows the parameters available for host connections. For passwords, it's easy: just use `ansible_password`, as shown in the examples in this repo. Unfortunately, there is no parameter like `ansible_ssh_private_key`. The closest we get seems to be `ansible_ssh_private_key_file`, but we can only pass a file here and not an inline value.

Do you think there is a way to make this work with the current plugin? Or is this a limitation? I'm currently facing a scenario where it's strictly preferable to use SSH keys over passwords for Ansible access, so it would be very useful for us to find a solution.

If you have any ideas or did prior research on this topic, I'd be very happy to hear your input. Thank you!

Cheers,
Joel
